
KNeighborsModelParams = 'models/kNeighborsParams.pkl'
LogisticRegressionModelParams = 'LogisticRegressionParams.pkl'
DecisionTreeModelParams = 'DecisionTreeParams.pkl'
RandomForestModelParams = 'RandomForestParams.pkl'
NeuralNetModelParams = 'PerceptronParams.pkl'

SymptomTypeMap = {
    'port_scanning' : 1, 'lfi' : 2, 'brute_ssh' : 3, 'auth_ssh' : 4, 'run_script' : 5,
    'transfer_tool' : 6, 'email_letter' : 7, 'run_file' : 8, 'start_new_thread' : 9,
    'code_injection' : 10, 'edit_params' : 11, 'data_exchange' : 12, 'proc_discovery_cmd' : 13,
    'proc_discovery_api' : 14, 'malicious_url' : 15, 'change_file_permission' : 16, 'scheduler' : 17,
    'js_file_execution' : 18, 'shell_environment' : 19, 'read_credential_file' : 20,
    'share_discovery' : 21, 'specific_tool' : 22, 'network_configuration' : 23, 'compress_tool' : 24,
    'hash_auth' : 25, 'auth_rdp' : 26, 'system_configuration' : 27
    }

CommandTypeMap = {
    'ls' : 1, 'pwd' : 2, 'vbs' : 3, 'curl' : 4, 'scp' : 5,
    'sftp' : 6, 'rsync' : 7, 'finger' : 8, 'wget' : 9,
    'attachment' : 10, 'executable_file' : 9, 'fork' : 10, 'create_proccess' : 11,
    'proccess_inject' : 12, 'registry_run_keys' : 13, 'dde' : 14,
    'ps' : 15, 'Get-Process' : 16, 'CreateToolhelp32Snapshot' : 17, 'cron' : 18,
    'task_manager' : 19, 'jscript' : 20, 'jxa' : 21, 'powershell' : 22, 'smb' : 23,
    'psexec' : 24, 'tor' : 25, 'mimicatz' : 26, 'imminent_monitor' : 27, 'cmd' : 28,
    'ipconfig' : 29, 'arp' : 30, 'nbstat' : 31, 'route' : 32, 'tar' : 33, 'zip' : 34,
    '7z' : 35, 'malware' : 36, 'rdp' : 37, 'systemctl' : 38, 'net' : 39,
    'id' : 40, 'groups' : 41, 'whoami' : 42, 'netstat' : 43, 'lsof' : 44
    }

MitreTypeMap = {
    'initial_access' : 1, 'execution' : 2, 'persistance' : 3,
    'privilege_escalation' : 4, 'defense_evasion' : 5, 'credential_access' : 6,
    'discovery' : 7, 'lateral_movement' : 8, 'collection' : 9,
    'exfiltration' : 10, 'command_and_control' : 11
}

MitreSubtypeMap = { 'domain_controller_authentication' : 1, 'browser_bookmark_discovery' : 2, 'system_language_discovery' : 3,
'component_object_model' : 4, 'exfiltration_over_usb' : 5, 'network_logon_script' : 6, 'ssh_hijacking' : 7,
'email_accounts' : 8, 'application_window_discovery' : 9, 'user_activity_based_checks' : 10, 'container_administration_command' : 11,
'asynchronous_procedure_call' : 12, 'network_security_appliances' : 13, 'search_open_websites_domains' : 14, 'windows_service' : 15,
'credentials_in_registry' : 16, 'software' : 17, 'one_way_communication' : 18, 'trusted_relationship' : 19,
'traffic_duplication' : 20, 'digital_certificates' : 21, 'acquire_infrastructure' : 22, 'path_interception_by_search_order_hijacking' : 23,
'windows_management_instrumentation_event_subscription' : 24, 'time_providers' : 25, 'domain_policy_modification' : 26, 'hypervisor' : 27,
'phishing' : 28, 'dns_server' : 29, 'create_process_with_token' : 30, 'application_layer_protocol' : 31,
'create_or_modify_system_process' : 32, 'non_standard_encoding' : 33, 'binary_padding' : 34, 'windows_management_instrumentation' : 35,
'keychain' : 36, 'non_application_layer_protocol' : 37, 'sid_history_injection' : 38, 'graphical_user_interface' : 39,
'lsa_secrets' : 40, 'ip_addresses' : 41, 'remote_email_collection' : 42, 'stored_data_manipulation' : 43,
'disable_or_modify_system_firewall' : 44, 'login_hook' : 45, 'password_managers' : 46, 'ntds' : 47,
'parent_pid_spoofing' : 48, 'deploy_container' : 49, 'applescript' : 50, 'mmc' : 51,
'internal_proxy' : 52, 'regsvcs_regasm' : 53, 'verclsid' : 54, 'domain_accounts' : 55,
'path_interception_by_path_environment_variable' : 56, 'domain_trust_modification' : 57, 'login_item' : 58, 'establish_accounts' : 59,
'gather_victim_network_information' : 60, 'archive_via_utility' : 61, 'native_api' : 62, 'exfiltration_over_physical_medium' : 63,
'search_open_technical_databases' : 64, 'compile_after_delivery' : 65, 'transport_agent' : 66, 'exploits' : 67,
'abuse_elevation_control_mechanism' : 68, 'credentials_in_files' : 69, 'additional_cloud_credentials' : 70, 'account_discovery' : 71,
'exfiltration_to_code_repository' : 72, 'remote_desktop_protocol' : 73, 'compromise_infrastructure' : 74, 'snmp_mib_dump' : 75,
'custom_cryptographic_protocol' : 76, 'thread_local_storage' : 77, 'application_access_token' : 78, 'private_keys' : 79,
'use_alternate_authentication_material' : 80, 'multi_factor_authentication_interception' : 81, 'gather_victim_identity_information' : 82, 'virtual_private_server' : 83,
'automated_exfiltration' : 84, 'data_destruction' : 85, 'steal_or_forge_kerberos_tickets' : 86, 'business_relationships' : 87,
'screensaver' : 88, 'code_signing_policy_modification' : 89, 'office_test' : 90, 'stage_capabilities' : 91,
'disable_cloud_logs' : 92, 'emond' : 93, 'exploitation_for_client_execution' : 94, 'supply_chain_compromise' : 95,
'securityd_memory' : 96, 'msbuild' : 97, 'uncommonly_used_port' : 98, 'time_based_evasion' : 99,
'external_defacement' : 100, 'authentication_package' : 101, 'thread_execution_hijacking' : 102, 'system_binary_proxy_execution' : 103,
'pre_os_boot' : 104, 'scan_databases' : 105, 'data_encrypted_for_impact' : 106, 'password_filter_dll' : 107,
'employee_names' : 108, 'email_collection' : 109, 'malicious_file' : 110, 'iis_components' : 111,
'malicious_image' : 112, 'hidden_files_and_directories' : 113, 're_opened_applications' : 114, 'remote_service_session_hijacking' : 115,
'standard_cryptographic_protocol' : 116, 'gather_victim_org_information' : 117, 'process_discovery' : 118, 'custom_command_and_control_protocol' : 119,
'cloud_service_dashboard' : 120, 'active_setup' : 121, 'shared_modules' : 122, 'symmetric_cryptography' : 123,
'pass_the_ticket' : 124, 'protocol_impersonation' : 125, 'file_transfer_protocols' : 126, 'deobfuscate_decode_files_or_information' : 127,
'firmware_corruption' : 128, 'outlook_home_page' : 129, 'bootkit' : 130, 'services_registry_permissions_weakness' : 131,
'data_from_network_shared_drive' : 132, 'exploitation_for_credential_access' : 133, 'component_object_model_and_distributed_com' : 134, 'launchctl' : 135,
'setuid_and_setgid' : 136, 'xpc_services' : 137, 'ntfs_file_attributes' : 138, 'group_policy_modification' : 139,
'external_remote_services' : 140, 'system_shutdown_reboot' : 141, 'data_encrypted' : 142, 'system_services' : 143,
'vba_stomping' : 144, 'whois' : 145, 'disable_windows_event_logging' : 146, 'data_from_cloud_storage_object' : 147,
'data_from_information_repositories' : 148, 'adversary_in_the_middle' : 149, 'spearphishing_attachment' : 150, 'dll_side_loading' : 151,
'network_share_connection_removal' : 152, 'data_transfer_size_limits' : 153, 'spearphishing_via_service' : 154, 'develop_capabilities' : 155,
'client_configurations' : 156, 'access_token_manipulation' : 157, 'keylogging' : 158, 'process_doppelgänging' : 159,
'system_network_configuration_discovery' : 160, 'data_manipulation' : 161, 'gui_input_capture' : 162, 'disk_structure_wipe' : 163,
'launch_daemon' : 164, 'match_legitimate_name_or_location' : 165, 'proc_memory' : 166, 'user_execution' : 167,
'reflection_amplification' : 168, 'terminal_services_dll' : 169, 'exfiltration_over_bluetooth' : 170, 'internal_defacement' : 171,
'vulnerabilities' : 172, 'shared_webroot' : 173, 'timestomp' : 174, 'saml_tokens' : 175,
'safe_mode_boot' : 176, 'compromise_hardware_supply_chain' : 177, 'web_session_cookie' : 178, 'clear_windows_event_logs' : 179,
'credentials_from_password_stores' : 180, 'unused_unsupported_cloud_regions' : 181, 'sharepoint' : 182, 'exfiltration_to_cloud_storage' : 183,
'email_forwarding_rule' : 184, 'systemd_service' : 185, 'cloud_infrastructure_discovery' : 186, 'threat_intel_vendors' : 187,
'appcert_dlls' : 188, 'web_portal_capture' : 189, 'network_service_discovery' : 190, 'hardware_additions' : 191,
'container_api' : 192, 'plist_modification' : 193, 'smb_windows_admin_shares' : 194, 'unix_shell' : 195,
'indirect_command_execution' : 196, 'dynamic_resolution' : 197, 'obtain_capabilities' : 198, 'network_device_configuration_dump' : 199,
'regsvr32' : 200, 'permission_groups_discovery' : 201, 'unix_shell_configuration_modification' : 202, 'external_proxy' : 203,
'accessibility_features' : 204, 'vdso_hijacking' : 205, 'social_media' : 206, 'web_protocols' : 207,
'cloud_accounts' : 208, 'os_credential_dumping' : 209, 'clear_linux_or_mac_system_logs' : 210, 'pluggable_authentication_modules' : 211,
'hidden_file_system' : 212, 'upload_malware' : 213, 'masquerade_task_or_service' : 214, 'lc_main_hijacking' : 215,
'server_software_component' : 216, 'sudo_and_sudo_caching' : 217, 'search_victim_owned_websites' : 218, 'exploit_public_facing_application' : 219,
'dynamic_linker_hijacking' : 220, 'linux_and_mac_file_and_directory_permissions_modification' : 221, 'new_service' : 222, 'code_repositories' : 223,
'forge_web_credentials' : 224, 'non_standard_port' : 225, 'system_firmware' : 226, 'port_knocking' : 227,
'powershell' : 228, 'registry_run_keys___startup_folder' : 229, 'launch_agent' : 230, 'invalid_code_signature' : 231,
'sip_and_trust_provider_hijacking' : 232, 'exfiltration_over_c2_channel' : 233, 'resource_hijacking' : 234, 'remote_services' : 235,
'link_target' : 236, 'compromise_software_dependencies_and_development_tools' : 237, 'sudo_caching' : 238, 'launchd' : 239,
'file_and_directory_permissions_modification' : 240, 'file_system_permissions_weakness' : 241, 'email_addresses' : 242, 'path_interception_by_unquoted_path' : 243,
'additional_email_delegate_permissions' : 244, 'network_device_cli' : 245, 'lsass_memory' : 246, 'rommonkit' : 247,
'endpoint_denial_of_service' : 248, 'vnc' : 249, 'hidden_window' : 250, 'application_shimming' : 251,
'at' : 252, 'container_orchestration_job' : 253, 'drive_by_compromise' : 254, 'phishing_for_information' : 255,
'mark_of_the_web_bypass' : 256, 'install_digital_certificate' : 257, 'right_to_left_override' : 258, 'bidirectional_communication' : 259,
'cloud_account' : 260, 'password_guessing' : 261, 'cached_domain_credentials' : 262, 'impair_defenses' : 263,
'process_hollowing' : 264, 'install_root_certificate' : 265, 'query_registry' : 266, 'audio_capture' : 267,
'obfuscated_files_or_information' : 268, 'network_share_discovery' : 269, 'exfiltration_over_asymmetric_encrypted_non_c2_protocol' : 270, 'file_and_directory_discovery' : 271,
'security_account_manager' : 272, 'network_boundary_bridging' : 273, 'ssh_authorized_keys' : 274, 'event_triggered_execution' : 275,
'system_information_discovery' : 276, 'additional_cloud_roles' : 277, 'domain_trust_discovery' : 278, 'space_after_filename' : 279,
'browser_session_hijacking' : 280, 'cor_profiler' : 281, 'msiexec' : 282, 'identify_roles' : 283,
'service_stop' : 284, 'identify_business_tempo' : 285, 'compromise_accounts' : 286, 'archive_via_custom_method' : 287,
'network_address_translation_traversal' : 288, 'exfiltration_over_symmetric_encrypted_non_c2_protocol' : 289, 'windows_remote_management' : 290, '_etc_passwd_and__etc_shadow' : 291,
'unsecured_credentials' : 292, 'system_owner_user_discovery' : 293, 'cloud_groups' : 294, 'command_and_scripting_interpreter' : 295,
'compromise_client_software_binary' : 296, 'multi_stage_channels' : 297, 'disable_or_modify_cloud_firewall' : 298, 'windows_command_shell' : 299,
'cmstp' : 300, 'application_deployment_software' : 301, 'multi_hop_proxy' : 302, 'spearphishing_link' : 303,
'golden_ticket' : 304, 'domain_properties' : 305, 'network_denial_of_service' : 306, 'modify_registry' : 307,
'clear_command_history' : 308, 'system_script_proxy_execution' : 309, 'service_execution' : 310, 'software_packing' : 311,
'network_topology' : 312, 'system_checks' : 313, 'revert_cloud_instance' : 314, 'scanning_ip_blocks' : 315,
'port_monitors' : 316, 'valid_accounts' : 317, 'indicator_removal_from_tools' : 318, 'change_default_file_association' : 319,
'system_network_connections_discovery' : 320, 'application_or_system_exploitation' : 321, 'screen_capture' : 322, 'llmnr_nbt_ns_poisoning_and_smb_relay' : 323,
'python' : 324, 'commonly_used_port' : 325, 'rogue_domain_controller' : 326, 'multilayer_encryption' : 327,
'email_hiding_rules' : 328, 'wordlist_scanning' : 329, 'systemd_timers' : 330, 'internet_connection_discovery' : 331,
'exploitation_for_defense_evasion' : 332, 'dll_search_order_hijacking' : 333, 'disabling_security_tools' : 334, 'reversible_encryption' : 335,
'domain_generation_algorithms' : 336, 'video_capture' : 337, 'dns_calculation' : 338, 'system_time_discovery' : 339,
'multi_factor_authentication_request_generation' : 340, 'modify_existing_service' : 341, 'software_deployment_tools' : 342, 'xdg_autostart_entries' : 343,
'drive_by_target' : 344, 'control_panel_items' : 345, 'input_capture' : 346, 'bash_history' : 347,
'proc_filesystem' : 348, 'create_cloud_instance' : 349, 'data_from_removable_media' : 350, 'firmware' : 351,
'outlook_rules' : 352, 'local_job_scheduling' : 353, 'debugger_evasion' : 354, 'network_trust_dependencies' : 355,
'container_and_resource_discovery' : 356, 'system_location_discovery' : 357, 'fallback_channels' : 358, 'local_account' : 359,
'scheduled_task' : 360, 'network_device_authentication' : 361, 'exfiltration_over_web_service' : 362, 'code_signing' : 363,
'active_scanning' : 364, 'print_processors' : 365, 'dynamic_data_exchange' : 366, 'credentials_in_files' : 367,
'rc_common' : 368, 'os_exhaustion_flood' : 369, 'virtualization_sandbox_evasion' : 370, 'login_items' : 371,
'xsl_script_processing' : 372, 'transmitted_data_manipulation' : 373, 'exploitation_of_remote_services' : 374, 'tool' : 375,
'portable_executable_injection' : 376, 'input_prompt' : 377, 'ssh' : 378, 'escape_to_host' : 379,
'web_services' : 380, 'modify_system_image' : 381, 'listplanting' : 382, 'reflective_code_loading' : 383,
'indicator_removal_on_host' : 384, 'rootkit' : 385, 'component_firmware' : 386, 'dns' : 387,
'botnet' : 388, 'data_obfuscation' : 389, 'domain_groups' : 390, 'resource_forking' : 391,
'extra_window_memory_injection' : 392, 'domain_fronting' : 393, 'clipboard_data' : 394, 'steal_web_session_cookie' : 395,
'hijack_execution_flow' : 396, 'disable_crypto_hardware' : 397, 'communication_through_removable_media' : 398, 'malicious_shell_modification' : 399,
'local_accounts' : 400, 'winlogon_helper_dll' : 401, 'application_exhaustion_flood' : 402, 'hide_artifacts' : 403,
'reduce_key_space' : 404, 'downgrade_system_image' : 405, 'inter_process_communication' : 406, 'web_cookies' : 407,
'protocol_tunneling' : 408, 'arp_cache_poisoning' : 409, 'installutil' : 410, 'cloud_service_discovery' : 411,
'upload_tool' : 412, 'steal_application_access_token' : 413, 'hooking' : 414, 'kernelcallbacktable' : 415,
'odbcconf' : 416, 'source' : 417, 'trap' : 418, 'at_linux' : 419,
'internal_spearphishing' : 420, 'visual_basic' : 421, 'default_accounts' : 422, 'template_injection' : 423,
'hardware' : 424, 'startup_items' : 425, 'disk_content_wipe' : 426, 'exfiltration_over_alternative_protocol' : 427,
'domains' : 428, 'outlook_forms' : 429, 'credential_api_hooking' : 430, 'distributed_component_object_model' : 431,
'patch_system_image' : 432, 'file_deletion' : 433, 'cloud_storage_object_discovery' : 434, 'masquerading' : 435,
'ingress_tool_transfer' : 436, 'services_file_permissions_weakness' : 437, 'implant_internal_image' : 438, 'rdp_hijacking' : 439,
'html_smuggling' : 440, 'standard_encoding' : 441, 'search_closed_sources' : 442, 'double_file_extension' : 443,
'proxy' : 444, 'mshta' : 445, 'weaken_encryption' : 446, 'search_engines' : 447,
'device_registration' : 448, 'boot_or_logon_initialization_scripts' : 449, 'cloud_instance_metadata_api' : 450, 'image_file_execution_options_injection' : 451,
'make_and_impersonate_token' : 452, 'software_discovery' : 453, 'local_groups' : 454, 'gather_victim_host_information' : 455,
'elevated_execution_with_prompt' : 456, 'traffic_signaling' : 457, 'peripheral_device_discovery' : 458, 'web_shell' : 459,
'downgrade_attack' : 460, 'pass_the_hash' : 461, 'malware' : 462, 'as_rep_roasting' : 463,
'confluence' : 464, 'office_application_startup' : 465, 'remote_data_staging' : 466, 'mail_protocols' : 467,
'build_image_on_host' : 468, 'data_encoding' : 469, 'account_access_removal' : 470, 'password_policy_discovery' : 471,
'password_cracking' : 472, 'purchase_technical_data' : 473, 'sql_stored_procedures' : 474, 'service_exhaustion_flood' : 475,
'exfiltration_over_unencrypted_non_c2_protocol' : 476, 'redundant_access' : 477, 'replication_through_removable_media' : 478, 'encrypted_channel' : 479,
'security_support_provider' : 480, 'rundll32' : 481, 'dead_drop_resolver' : 482, 'direct_network_flood' : 483,
'archive_via_library' : 484, 'modify_authentication_process' : 485, 'vulnerability_scanning' : 486, 'executable_installer_file_permissions_weakness' : 487,
'forced_authentication' : 488, 'junk_data' : 489, 'shortcut_modification' : 490, 'logon_script_windows' : 491,
'local_email_collection' : 492, 'control_panel' : 493, 'inhibit_system_recovery' : 494, 'execution_guardrails' : 495,
'pubprn' : 496, 'browser_extensions' : 497, 'histcontrol' : 498, 'code_signing_certificates' : 499,
'web_service' : 500, 'cdns' : 501, 'disable_or_modify_tools' : 502, 'multiband_communication' : 503,
'gatekeeper_bypass' : 504, 'credential_stuffing' : 505, 'kerberoasting' : 506, 'remote_access_software' : 507,
'dynamic_link_library_injection' : 508, 'server' : 509, 'data_staged' : 510, 'dylib_hijacking' : 511,
'taint_shared_content' : 512, 'service_registry_permissions_weakness' : 513, 'security_software_discovery' : 514, 'path_interception' : 515,
'social_media_accounts' : 516, 'environmental_keying' : 517, 'local_data_staging' : 518, 'boot_or_logon_autostart_execution' : 519,
'process_argument_spoofing' : 520, 'group_policy_discovery' : 521, 'powershell_profile' : 522, 'lsass_driver' : 523,
'office_template_macros' : 524, 'appinit_dlls' : 525, 'windows_admin_shares' : 526, 'windows_credential_manager' : 527,
'email_account' : 528, 'dhcp_spoofing' : 529, 'disk_wipe' : 530, 'password_spraying' : 531,
'dns_passive_dns' : 532, 'rc_scripts' : 533, 'llmnr_nbt_ns_poisoning_and_relay' : 534, 'network_sniffing' : 535,
'component_object_model_hijacking' : 536, 'bypass_user_account_control' : 537, 'credentials_from_web_browsers' : 538, 'data_compressed' : 539,
'asymmetric_cryptography' : 540, 'ptrace_system_calls' : 541, 'defacement' : 542, 'dcsync' : 543,
'automated_collection' : 544, 'scheduled_transfer' : 545, 'determine_physical_locations' : 546, 'bits_jobs' : 547,
'mavinject' : 548, 'compiled_html_file' : 549, 'steganography' : 550, 'rename_system_utilities' : 551,
'modify_cloud_compute_infrastructure' : 552, 'create_account' : 553, 'compromise_software_supply_chain' : 554, 'subvert_trust_controls' : 555,
'netsh_helper_dll' : 556, 'run_virtual_instance' : 557, 'silver_ticket' : 558, 'token_impersonation_theft' : 559,
'indicator_blocking' : 560, 'fast_flux_dns' : 561, 'tftp_boot' : 562, 'scripting' : 563,
'exploitation_for_privilege_escalation' : 564, 'runtime_data_manipulation' : 565, 'javascript' : 566, 'account_manipulation' : 567,
'lc_load_dylib_addition' : 568, 'transfer_data_to_cloud_account' : 569, 'credentials' : 570, 'create_snapshot' : 571,
'group_policy_preferences' : 572, 'brute_force' : 573, 'data_from_configuration_repository' : 574, 'cron' : 575,
'impair_command_history_logging' : 576, 'exfiltration_over_other_network_medium' : 577, 'sudo' : 578, 'windows_file_and_directory_permissions_modification' : 579,
'delete_cloud_instance' : 580, 'plist_file_modification' : 581, 'process_injection' : 582, 'domain_account' : 583,
'data_from_local_system' : 584, 'remote_system_discovery' : 585, 'system_service_discovery' : 586, 'add_ins' : 587,
'trusted_developer_utilities_proxy_execution' : 588, 'malicious_link' : 589, 'direct_volume_access' : 590, 'lateral_tool_transfer' : 591,
'spearphishing_service' : 592, 'archive_collected_data' : 593, 'hidden_users' : 594, 'scheduled_task_job' : 595,
'kernel_modules_and_extensions' : 596 }
